id: P86106B9C
initial_creation_type: ocr
source_metadata:
  volumes:
    105823b1bd2e4d7bb6d988171235623d:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: མདོ་སྡེ་དགོངས་པ་ངེས་པར་འགྲེལ་པའི་མདོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1880
      volume_number: 116
